# Generated by Django 3.2.6 on 2021-10-29 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='citry',
            new_name='city',
        ),
    ]
